SustiVest.Web/Controllers/CompanyController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SustiVest.Data.Entities;
using SustiVest.Data.Services;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace SustiVest.Web.Controllers
{
    // [Authorize]
    public class CompanyController : BaseController
    {
        private readonly ICompanyService _svc;
        private readonly Permissions _permissions;

        public CompanyController(ICompanyService svc, Permissions permissions)
        {
            _svc = svc;
            _permissions = permissions;
        }

        // GET /company
        //editted from Index to CompanyIndex
        [HttpGet]
        public IActionResult CompanyIndex(int page = 1, int size = 20, string order = "companyname", string direction = "asc")
        {
            // load Companies using service and pass to view

            var table = _svc.GetCompanies(page, size, order, direction);
            if (!User.IsInRole("admin") && !User.IsInRole("analyst"))
            {
                table.Data = table.Data.Where(c => c.ProfileStatus == "Approved").ToList();

                return View(table);
            }
            return View(table);
        }

        // GET /company/details/{CR_No}
        [HttpGet]
        public IActionResult CompanyDetails(string crNo)
        {
            var company = _svc.GetCompany(crNo);
            // check if company is null and alert/redirect 
            if (company is null)
            {
                Alert("company not found", AlertType.warning);
                return RedirectToAction(nameof(CompanyIndex));
            }

            if (!User.IsInRole("admin") && !User.IsInRole("analyst"))
            {
                if (company.ProfileStatus != "Approved")
                {
                    Alert("company not found", AlertType.warning);
                    return RedirectToAction(nameof(CompanyIndex));
                }
            }

            return View(company);
        }

        // GET: /company/create
        [Authorize(Roles = "admin, borrower, analyst")]
        [HttpGet]
        public IActionResult Create()
        {
            // display blank form to create company
            var currentUserId = int.Parse(User.FindFirst(ClaimTypes.Sid).Value);

            // Create a new Company instance and set the RepId property
            var company = new Company
            {
                RepId = currentUserId
            };
            return View(company);
        }

        // POST /company/create
        // [Authorize(Roles="admin,support")]
        [Authorize(Roles = "admin, borrower, analyst")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create([Bind("CRNo, TaxID, CompanyName, Industry, DateOfEstablishment, Activity, Type, ShareholderStructure, RepId, ProfileStatus")] Company c)
        {
            // validate company name is unique
            if (_svc.GetCompanyByName(c.CompanyName) != null)
            {
                ModelState.AddModelError(nameof(c.CompanyName), "Please write unique company name.");
            }

            // complete POST action to add company
            if (ModelState.IsValid)
            {
                // call service AddCompany method using data in s
                Console.WriteLine($"company:2222222 {c} NAME {c.CompanyName}");
                var company = _svc.AddCompany(c);
                if (company is null)
                {
                    Alert("Encountered issue creating company profile.", AlertType.warning);
                    return RedirectToAction(nameof(CompanyIndex));
                }
                Alert("Thank you for creating a SustiVest profile. Your Request submitted for approval.", AlertType.success);
                return RedirectToAction(nameof(CompanyIndex));
            }
            // redisplay the form for editing as there are validation errors
            return View(c);
        }


        [Authorize(Roles = "admin, analyst")]
        [HttpGet]
        public IActionResult ApproveCompany(string crNo)
        {
            var company = _svc.GetCompany(crNo);
            Console.WriteLine($"company: {company} name:{company.CompanyName}");
            if (company == null)
            {
                Alert("Company not found", AlertType.warning);
                return RedirectToAction(nameof(CompanyIndex));
            }
            return View("CompanyDetails", company);
        }


        [Authorize(Roles = "admin, analyst")]
        [HttpPost]
        public IActionResult ApproveCompany(Company c)
        {
            var company = _svc.GetCompany(c.CRNo);
            Console.WriteLine($"2company: {company} name:{company.CompanyName}");

            if (company == null)
            {
                Console.WriteLine($"company null {company} name:{company.CompanyName}");
                Alert("Company not found", AlertType.warning);
                return RedirectToAction(nameof(CompanyIndex));
            }
            if (ModelState.IsValid)
            {
                var approved = _svc.Approve(company);
                Console.WriteLine($"3company: {approved} name:{approved.CompanyName}");

                if (approved == null)
                {
                    Alert("Could not post company profile", AlertType.warning);
                    return RedirectToAction(nameof(CompanyIndex));
                }
                // Redirect back to view the company details
                Alert("Company profile posted successfully", AlertType.warning);
                return RedirectToAction(nameof(CompanyDetails), new { crNo = approved.CRNo });

            }
          Console.WriteLine($"4company: {c} name:{c.CompanyName}");

            return View("CompanyDetails", c);
        }

        // GET /company/edit/{id}
        [Authorize(Roles = "admin, borrower, analyst")]
        [HttpGet]
        public IActionResult Edit(string crNo)
        {
            // load the company using the service
            var company = _svc.GetCompany(crNo);

            // check if company is null and Alert/Redirect
            if (company is null)
            {
                Alert("Company not found", AlertType.warning);
                return RedirectToAction(nameof(CompanyIndex));
            }
            var userId = int.Parse(User.FindFirst(ClaimTypes.Sid).Value);

            if (!_permissions.IsUserAuthorizedToEditCompany(crNo, userId, httpContext: HttpContext))
            {
                Alert("You are not authorized to edit this company profile", AlertType.warning);
                return RedirectToAction(nameof(CompanyDetails), new { crNo = crNo });
            }

            // // Pass the company to the view for editing
            return View("Edit", company);  
        }

        // POST /company/edit/{id}
        [Authorize(Roles = "admin, borrower, analyst")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Company c)
        {
            // check if company name already exists and is not owned by company being edited 

            // Check if the ModelState is valid (i.e., no validation errors)
                Console.WriteLine($"company: {c} name:{c.CompanyName}");

            if (ModelState.IsValid)
            {
                // Complete POST action to save company changes
                var updated = _svc.UpdateCompany(c);
                Console.WriteLine($"company: {updated} name:{updated.CompanyName}");

                if (updated == null)
                {
                    Alert("Encountered issue while updating company", AlertType.warning);
                    return RedirectToAction(nameof(CompanyIndex));
                }
                else
                {
                    // Redirect back to view the company details
                    return RedirectToAction(nameof(CompanyDetails), new { crNo = updated.CRNo });
                }
            }
            Console.WriteLine($"Model Invalid!!");

            // Redisplay the form for editing as validation errors
            return View(c);
        }


        // GET / company/delete/{id}
        [Authorize(Roles = "admin, analyst")]
        [HttpGet]
        public IActionResult Delete(string crNo)
        {
            // load the company using the service
            var userId = int.Parse(User.FindFirst(ClaimTypes.Sid).Value);
            var company = _svc.GetCompany(crNo);
            // check the returned company is not null and if so return NotFound()
            if (company == null)
            {
                Alert("Company not found", AlertType.warning);
                return RedirectToAction(nameof(CompanyIndex));
            }

            if (!_permissions.IsUserAuthorizedToEditCompany(crNo, userId, httpContext: HttpContext))
            {
                return RedirectToAction(nameof(CompanyDetails), new { crNo = crNo });
            }

            // pass company to view for deletion confirmation
            return View(company);
        }

        // POST /company/delete/{id}
        [Authorize(Roles = "admin, analyst")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(string crNo)
        {
            // delete company via service
            var deleted = _svc.DeleteCompany(crNo);
            if (deleted)
            {
                Alert("Company deleted successfully.", AlertType.success);
            }
            else
            {
                Alert("Company could not  be deleted", AlertType.warning);
            }

            // redirect to the index view
            return RedirectToAction(nameof(CompanyIndex));
        }
    }
}

SustiVest.Web/Views/Shared/Components/SortOrder/SortOrderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SustiVest.Web.Views.Shared.Components;

[ViewComponent]
public class SortOrderViewComponent : ViewComponent
{

    public IViewComponentResult Invoke(string field="Id", string orderby="Id", string direction = "asc")
    {      
        return View("Default", new SortOrderProps(field.ToLower(), orderby.ToLower(), direction.ToLower()) );
    }
}

public record SortOrderProps(string Field ="Id", string OrderBy="Id", string Direction="asc");

SustiVest.Web/Views/Company/CompanyDetails.cshtml
@model SustiVest.Data.Entities.Company
@using System.Security.Claims;

<partial name="_BreadCrumbs" model=@(new [] { ("/","Home"), ("/company/companyindex","companies"),
    ("",$"{Model.CompanyName}") }) />


<div class="card rounded shadow p-4">
    <!-- Display student details -->
    <div class="row">
        <!-- Details and Navigation -->
        <div class="col-8 d-flex flex-column justify-content-between">
            <!-- Company details -->
            <div>
                <h2 class="mb-4" style="color: #097969;">@Model.CompanyName Profile</h2>
                <dl class="row">

                    <dt class="col-4 pb-1">CRNo</dt>
                    <dd class="col-8 pb-1">@Model.CRNo</dd>

                    <dt class="col-4 pb-1">Tax ID</dt>
                    <dd class="col-8 pb-1">@Model.TaxID</dd>

                    <dt class="col-4 pb-1">Industry</dt>
                    <dd class="col-8 pb-1">@Model.Industry</dd>

                    <dt class="col-4 pb-1">Eastablished On</dt>
                    <dd class="col-8 pb-1">@Model.DateOfEstablishment</dd>

                    <dt class="col-4 pb-1">Activity</dt>
                    <dd class="col-8 pb-1">@Model.Activity</dd>

                    <dt class="col-4 pb-1">Type</dt>
                    <dd class="col-8 pb-1">@Model.Type</dd>

                    <dt class="col-4 pb-1">Shareholders</dt>
                    <dd class="col-8 pb-1">@Model.ShareholderStructure</dd>

                    @if (User.IsInRole("admin") || User.IsInRole("analyst"))
                    {
                        <dt class="col-4 pb-1">Status</dt>
                        <dd class="col-8 pb-1">@Model.ProfileStatus</dd>
                    }
                </dl>
            </div>

            <!-- Navigation links -->
            <div>
                <!-- navigation link to Index action -->
                <a asp-action="Index" class="btn btn-sm btn-outline-success" aria-label="company list">
                    <i class="bi bi-list" title="company list"></i>
                    <span class="ms-1 d-none d-md-inline">List</span>
                </a>


                <a asp-action="Edit" asp-route-crNo="@Model.CRNo" class="btn btn-sm btn-outline-secondary"
                    aria-label="edit company">
                    <i class="bi bi-pen-fill text-secondary" title="edit company"></i>
                    <span class="ms-1 d-none d-md-inline">Edit</span>
                </a>

                <a asp-controller="FinanceRequest" asp-action="CreateRequest" asp-route-crNo="@Model.CRNo"
                    class="btn btn-sm text-white" aria-label="request finance" style="background-color: #097969;">
                    <i class="bi bi-cash-stack text-white" title="request finance"></i>
                    <span class="ms-1 d-none d-md-inline">Request Finance</span>
                </a>


                <!-- alternate delete modal activation button -->
                <button type="button" class="btn btn-sm btn-outline-danger" aria-label="delete company"
                    data-bs-toggle="modal" data-bs-target="#deleteCompanyModal">
                    <i class="bi bi-trash text-danger"></i> Delete
                </button>

                <form asp-controller="Company" asp-action="ApproveCompany" asp-route-crNo="@Model.CRNo" method="post">
                    <button type="submit" class="btn btn-sm btn-outline-success" aria-label="approve company">
                        <i class="bi bi-check-circle me-2" title="approve company"
                            aria-label="approve company"></i>Approve
                    </button>
                </form>
            </div>
        </div>

    </div>
</div>
<!-- Finance Requests -->
@{
    if (User.Identity.IsAuthenticated)
    {
        var userId = int.Parse(User.FindFirst(ClaimTypes.Sid).Value);
        if (Model.RepId == userId)
        {
            <div class="card rounded shadow p-4 mt-4">
                <partial name="_FinanceRequests" />
            </div>
        }
    }
}
<!-- Delete Modal -->
<partial name="_DeleteModal" />
<style>
    .bi {
        color: #097969;
    }
</style>

SustiVest.Web/Views/Company/CompanyIndex.cshtml
@model Paged<Company>

<partial name="_BreadCrumbs" model=@(new [] { ("/","Home"), ("","Companies") }) />

<div class="card border rounded shadow p-4">

    <!-- Title bar -->
    <div class="d-flex align-items-center justify-content-between">
        <h3>Company</h3>

        <a class="btn btn-sm btn-primary" asp-action="create" title="add company" aria-label="add company"
            style="background-color: #097969;">
            <i class="bi bi-plus" style="color: white;"></i> Create
        </a>

    </div>

    <!-- Search bar -->

    @* <form id="searchForm" class="form-inline mt-3">
    <div class="input-group">
    <select id="searchEntity" class="form-select">
    <option value="company">Company</option>
    <option value="financeRequest">Finance Request</option>
    <!-- Add more options for other entities as needed -->
    </select>
    <select id="searchProperty" class="form-select">
    <option value="all">All Properties</option>
    <option value="crNo">CRNo</option>
    <option value="taxid">Tax ID</option>
    <option value="companyname">Company Name</option>
    <option value="industry">Industry</option>
    <option value="type">Type</option>
    </select>

    <input type="text" id="searchQuery" class="form-control"
    placeholder="Search by Company Name, CRNo, Industry, etc." aria-label="Search" />
    <button type="button" id="searchButton" class="btn btn-primary"><i class="bi bi-search"></i>
    Search</button>
    </div>
    </form> *@

    @* <div id="searchResults" class="mt-4">
    <!-- Search results will be displayed here -->
    </div> *@

    <!-- List of companies -->
    <table class="table table-hover mt-4">
        <thead>
            <tr>
                <thead>
                    <tr>
                        <th>
                            Commercial Registration
                            <a asp-action="CompanyIndex" asp-route-order="crNo" asp-route-direction=@Model.Direction
                                asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                                <vc:sort-order field="crNo" orderby=@Model.OrderBy direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Name
                            <a asp-action="CompanyIndex" asp-route-order="companyname"
                                asp-route-direction=@Model.Direction asp-route-page=@Model.CurrentPage
                                asp-route-size=@Model.PageSize>
                                <vc:sort-order field="companyname" orderby=@Model.OrderBy direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Industry
                            <a asp-action="CompanyIndex" asp-route-order="industry" asp-route-direction=@Model.Direction
                                asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                                <vc:sort-order field="industry" orderby=@Model.OrderBy direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Established
                            <a asp-action="CompanyIndex" asp-route-order="dateofestablishment"
                                asp-route-direction=@Model.Direction asp-route-page=@Model.CurrentPage
                                asp-route-size=@Model.PageSize>
                                <vc:sort-order field="dateofestablishment" orderby=@Model.OrderBy
                                    direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Activity
                            <a asp-action="CompanyIndex" asp-route-order="activity" asp-route-direction=@Model.Direction
                                asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                                <vc:sort-order field="activity" orderby=@Model.OrderBy direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Type
                            <a asp-action="CompanyIndex" asp-route-order="type" asp-route-direction=@Model.Direction
                                asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                                <vc:sort-order field="type" orderby=@Model.OrderBy direction=@Model.Direction />
                            </a>
                        </th>
                        <th>
                            Shareholders
                            <a asp-action="CompanyIndex" asp-route-order="shareholderstructure"
                                asp-route-direction=@Model.Direction asp-route-page=@Model.CurrentPage
                                asp-route-size=@Model.PageSize>
                                <vc:sort-order field="shareholderstructure" orderby=@Model.OrderBy
                                    direction=@Model.Direction />
                            </a>
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
        <tbody>
                    @foreach (var c in (Model.Data))
                    {
                <tr>
                    <td>@c.CRNo</td>
                    <td>@c.CompanyName</td>
                    <td>@c.Industry</td>
                    <td>@c.DateOfEstablishment</td>
                    <td>@c.Activity</td>
                    <td>@c.Type</td>
                    <td>@c.ShareholderStructure</td>
                    <td>
                        <a asp-action="CompanyDetails" asp-route-crNo="@c.CRNo">
                            <i class="bi bi-display-fill me-2" title="view company" arial-label="view company"></i>
                        </a>
                        <a asp-action="Edit" asp-route-crNo=@c.CRNo>
                            <i class="bi bi-pencil-fill me-2" title="edit company" aria-label="edit company"></i>
                        </a>
                        <a asp-action="Delete" asp-route-crNo=@c.CRNo>
                            <i class="bi bi-trash-fill me-2" title="delete company" aria-label="delete company"></i>
                        </a>

                    </td>
                </tr>
                    }
        </tbody>
    </table>

    <style>
        .bi {
            color: #097969;
        }
    </style>
    <style>
        .btn-primary:hover {
            background-color: #0b8a6c;
        }
    </style>

SustiVest.Web/Views/Company/Create.cshtml
@model Company 

<partial name="_BreadCrumbs" model=@(new [] {
    ("/","Home"),
    ($"/company/companyindex","Companies"),
    ("","Create Company")
}) />

<div class="card rounded shadow p-4">
    <h3>Create Company</h3>
    <form asp-action="Create" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input type="hidden" asp-for="RepId"/>
        <input type="hidden" asp-for="ProfileStatus"/>


        <div class="mt-3">
            <label asp-for="CRNo" class="form-label"></label>
            <input asp-for="CRNo" class="form-control" />
            <span asp-validation-for="CRNo" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="TaxID" class="form-label"></label>
            <input asp-for="TaxID" class="form-control" />
            <span asp-validation-for="TaxID" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="CompanyName" class="form-label"></label>
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Industry" class="form-label"></label>
            <input asp-for="Industry" class="form-control" />
            <span asp-validation-for="Industry" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="DateOfEstablishment" class="form-label"></label>
            <input asp-for="DateOfEstablishment" class="form-control" />
            <span asp-validation-for="DateOfEstablishment" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Activity" class="form-label"></label>
            <input asp-for="Activity" class="form-control" />
            <span asp-validation-for="Activity" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Type" class="form-label"></label>
            <input asp-for="Type" class="form-control" />
            <span asp-validation-for="Type" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="ShareholderStructure" class="form-label"></label>
            <input asp-for="ShareholderStructure" class="form-control" />
            <span asp-validation-for="ShareholderStructure" class="text-danger"></span>
        </div>

        @if (User.IsInRole("analyst") || User.IsInRole("admin"))
        {
            <div class="mt-3">
                <label asp-for="RepId" class="form-label"></label>
                <input asp-for="RepId" class="form-control" />
                <span asp-validation-for="RepId" class="text-danger"></span>
            </div>
        
        <div class="mt-3">
            <label asp-for="ProfileStatus" class="form-label"></label>
            <input asp-for="ProfileStatus" class="form-control" />
            <span asp-validation-for="ProfileStatus" class="text-danger"></span>
        </div>
        }
        
        <div class="mt-3">
            <button type="submit" name="submit" class="btn btn-primary" aria-label="save">Save</button>
            <a class="btn btn-secondary" asp-action="CompanyIndex" aria-label="cancel">Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SustiVest.Web/Views/Company/Delete.cshtml
@model Company

<partial name="_BreadCrumbs" model=@(new [] { ("/","Home"), ("/company","Companies"), ("",$"{Model.CompanyName}") }) />

<div class="card rounded shadow p-4">
    <!-- Display company details -->
    <div class="row">
        <!-- Details and Navigation -->
        <div class="col-8 d-flex flex-column justify-content-between">
            <!-- Company details -->
            <div>
                <h2 class="mb-4 text-primary">@Model.CompanyName Profile</h2>
                <dl class="row">
                    <!-- ... (other properties) ... -->
                </dl>
            </div>

            <!-- Navigation links -->
            <div>
                <a asp-action="Index" class="btn btn-sm btn-outline-primary" aria-label="company list">
                    <i class="bi bi-list" title="company list"></i>
                    <span class="ms-1 d-none d-md-inline">List</span>
                </a>

                <a asp-action="Edit" asp-route-crNo="@Model.CRNo" class="btn btn-sm btn-outline-secondary"
                    aria-label="edit company">
                    <i class="bi bi-pen-fill" title="edit company"></i>
                    <span class="ms-1 d-none d-md-inline">Edit</span>
                </a>

                <form method="post" asp-action="DeleteConfirm" asp-route-assessmentNo="@Model.CRNo"
                    class="d-inline">
                    
                    <button type="submit" class="btn btn-sm btn-outline-danger" aria-label="delete company">
                        <i class="bi bi-trash-fill" title="delete company"></i>
                        <span class="ms-1 d-none d-md-inline">Delete</span>
                    </button>
                </form>


                <a asp-controller="FinanceRequest" asp-action="CreateRequest" asp-route-crNo="@Model.CRNo"
                    class="btn btn-sm btn-outline-primary" aria-label="request finance">
                    <i class="bi bi-cash-stack" title="request finance"></i>
                    <span class="ms-1 d-none d-md-inline">Request Finance</span>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Finance Requests -->
<div class="card rounded shadow p-4 mt-4">
    <partial name="_FinanceRequests" />
</div>

<!-- JavaScript to display the delete confirmation dialog -->
<script>
    document.getElementById("deleteCompanyButton").addEventListener("click", function () {
        if (confirm("Are you sure you want to delete this company?")) {
            // User clicked "Yes," redirect to the DeleteConfirm action
            window.location.href = "/Company/DeleteConfirm?crno=@Model.CRNo";
        }
    });
</script>

SustiVest.Web/Views/Company/Edit.cshtml
@model Company 

<partial name="_BreadCrumbs" model=@(new [] {
    ("/","Home"),
    ($"/company/companyindex","Companies"),
    ("","Edit Company")
}) />

<div class="card rounded shadow p-4">
    <h3>Edit Company</h3>
    <form asp-action="Edit" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input type="hidden" asp-for="CRNo" class="form-control"/> 
        <input type="hidden" asp-for="RepId"/>
        <input type="hidden" asp-for="ProfileStatus"/>
        <div class="mt-3">
            <label asp-for="CRNo" class="form-label"></label>
            <input asp-for="CRNo" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="mt-3">
            <label asp-for="CompanyName" class="form-label"></label>
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Industry" class="form-label"></label>
            <input asp-for="Industry" class="form-control" />
            <span asp-validation-for="Industry" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="DateOfEstablishment" class="form-label"></label>
            <input asp-for="DateOfEstablishment" class="form-control" />
            <span asp-validation-for="DateOfEstablishment" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Activity" class="form-label"></label>
            <input asp-for="Activity" class="form-control" />
            <span asp-validation-for="Activity" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Type" class="form-label"></label>
            <input asp-for="Type" class="form-control" />
            <span asp-validation-for="Type" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="ShareholderStructure" class="form-label"></label>
            <input asp-for="ShareholderStructure" class="form-control" />
            <span asp-validation-for="ShareholderStructure" class="text-danger"></span>
        </div>
             
        <div class="mt-3">
            <label asp-for="RepId" class="form-label"></label>
            <input asp-for="RepId" class="form-control" />
            <span asp-validation-for="RepId" class="text-danger"></span>
        </div>

    
        <div class="mt-3">
            <label asp-for="ProfileStatus" class="form-label"></label>
            <input asp-for="ProfileStatus" class="form-control" />
            <span asp-validation-for="ProfileStatus" class="text-danger"></span>
        </div>
    

        <div class="mt-3">
            <button type="submit" name="submit" class="btn btn-primary" aria-label="save" >Save</button>
            <a class="btn btn-secondary" asp-action="CompanyIndex" aria-label="cancel">Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SustiVest.Web/Views/Company/_DeleteModal.cshtml
@model Company

<!-- _DeleteModal.cshtml -->
<div class="modal fade" id="deleteCompanyModal" tabindex="-1" role="dialog" aria-labelledby="deleteCompanyModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteCompanyModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this company?</p>
            </div>
            <div class="modal-footer">

                <form asp-action="DeleteConfirm" type="post">
                    <input type="hidden" asp-for="CRNo" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>