SustiVest.Web/Controllers/AssessmentsController.cs
using Microsoft.AspNetCore.Mvc;
using SustiVest.Data.Entities;
using SustiVest.Data.Services;
using Microsoft.AspNetCore.Authorization;

namespace SustiVest.Web.Controllers
{
    [Authorize]
    public class AssessmentsController : BaseController
    {
        private readonly IAssessmentsService _svc;
        private readonly ICompanyService _companyService;
        private readonly Permissions _permissions;

        public AssessmentsController(IAssessmentsService svc, ICompanyService companyService, Permissions permissions)
        {
            _svc = svc;
            _companyService = companyService;
            _permissions = permissions;
        }

        // GET /assessments
        [Authorize(Roles = "admin, analyst")]
        public ActionResult Index(int page = 1, int size = 10, string orderBy = "CompanyName", string direction = "asc")
        {
            var table = _svc.GetAssessments(page, size, orderBy, direction);
            return View(table);
        }


        // GET /assessments/details/{requestNo}/{analystNo}
        [Authorize(Roles = "admin, analyst, borrower, investor")]
        public IActionResult Details(int? assessmentNo, int? requestNo)
        {

            var assessment= assessmentNo.HasValue ? _svc.GetAssessment(assessmentNo.Value): _svc.GetAssessmentByRequestNo(requestNo.Value);

            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);

            // if (assessmentNo.HasValue)
            // {
            //     // Try to get the assessment by assessment number.
            //     assessment = _svc.GetAssessment(assessmentNo.Value);
            // }
            // else if (requestNo.HasValue)
            // {
            //     // Try to get the assessment by request number.
            //     assessment = _svc.GetAssessmentByRequestNo(requestNo.Value);
            // }

            if (assessment == null)
            {
                Alert("Assessment not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            if (assessment.Posted)
            {
                return View(assessment);
            }
            if (!_permissions.IsUserAuthorizedToEditCompany(assessment.CRNo, userId, httpContext: HttpContext) && !User.IsInRole("admin") && !User.IsInRole("analyst"))
            {
                Alert("You are not authorized to view this assessment", AlertType.warning);
                return RedirectToAction("CompanyIndex", "Company");
            }

            return View(assessment);
        }


        // GET: /assessments/create

        [Authorize(Roles = "admin, analyst")]
        public IActionResult Create(int requestNo, string crNo)
        {

            return View();
        }

        // POST /assessments/create
        [Authorize(Roles = "admin, analyst")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create([Bind("AssessmentNo, RequestNo, AnalystNo, Sales, EBITDA, DSR, CCC, RiskRating, MarketPosition, RepaymentStatus, FinancialLeverage, WorkingCapital, OperatingAssets, CRNo, TotalAssets, NetEquity")] Assessments a)
        {
            if (User.IsInRole("analyst"))
            {
                a.AnalystNo = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);
            }

            if (ModelState.IsValid)
            {
                var assessment = _svc.AddAssessment(a);

                if (assessment != null)
                {
                    return RedirectToAction(nameof(Details), new { assessmentNo = assessment.AssessmentNo });
                }

                Alert("Encountered an issue while creating the assessment.", AlertType.warning);
            }

            // Redisplay the form for editing as there are validation errors
            return View(a);
        }

        [Authorize(Roles = "admin, borrower")]
        [HttpPost]
        public IActionResult Post(int assessmentNo)
        {
            var assessment = _svc.GetAssessment(assessmentNo);
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);

            if (assessment == null)
            {
                Alert("Assessment not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            if (!_permissions.IsUserAuthorizedToEditCompany(assessment.CRNo, userId, httpContext: HttpContext)&&!User.IsInRole("admin"))
            {
                Alert("You are not authorized to post this assessment", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            var posted = _svc.PostAssessment(assessmentNo);

            if (posted != null)
            {
                Alert("Assessment Posted", AlertType.success);
            }
            else
            {
                Alert("Encountered an issue while posting the assessment.", AlertType.warning);
            }

            return RedirectToAction(nameof(Details), new { assessmentNo = assessment.AssessmentNo });
        }

        // GET /assessments/edit/{requestNo}/{analystNo]
        [Authorize(Roles = "admin, analyst")]
        [HttpGet]
        public IActionResult Edit(int assessmentNo)
        {
            var assessment = _svc.GetAssessment(assessmentNo);
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);

            if (assessment == null)
            {
                Alert("Assessment not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            if (!_permissions.IsUserAuthorizedToEditAssessment(assessment.AssessmentNo, userId, httpContext: HttpContext))
            {
                Alert("You are not authorized to edit this assessment", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);
        }


        // POST /assessments/edit/{requestNo}/{analystNo]
        [Authorize(Roles = "admin, analyst")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(int assessmentNo, [Bind("RequestNo, AnalystNo, Sales, EBITDA, DSR, CCC, RiskRating, MarketPosition, RepaymentStatus, FinancialLeverage, WorkingCapital, OperatingAssets, CRNo, TotalAssets, NetEquity")] Assessments a)
        {
            var assessment = _svc.GetAssessment(assessmentNo);

            // Check if an assessment with the same RequestNo and AnalystNo exists
            if (ModelState.IsValid)
            {
                var updated = _svc.UpdateAssessment(assessmentNo, a.RequestNo, a.AnalystNo, a.Sales, a.EBITDA, a.DSR, a.CCC, a.RiskRating, a.MarketPosition, a.RepaymentStatus, a.FinancialLeverage, a.WorkingCapital, a.OperatingAssets, a.CRNo, a.TotalAssets, a.NetEquity);

                if (updated != null)
                {
                    Alert("Assessment Updated", AlertType.success);

                    return RedirectToAction(nameof(Details), new { assessmentNo = updated.AssessmentNo });

                }

                Alert("Encountered an issue while updating the assessment.", AlertType.warning);
            }

            // Redisplay the form for editing as there are validation errors
            return View(a);
        }

        // GET /assessments/delete/{requestNo}/{analystNo]
        [Authorize(Roles = "admin, analyst")]
        public IActionResult Delete(int assessmentNo)
        {
            var assessment = _svc.GetAssessment(assessmentNo);
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);
            if (assessment == null)
            {
                Alert("Assessment not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            if (!_permissions.IsUserAuthorizedToEditAssessment(assessment.AssessmentNo, userId, httpContext: HttpContext))
            {
                Alert("You are not authorized to delete this assessment", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);

        }

        // POST /assessments/delete/{requestNo}/{analystNo]
        [Authorize(Roles = "admin, analyst")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult DeleteConfirm(int assessmentNo)
        {
            var deleted = _svc.DeleteAssessment(assessmentNo);

            if (deleted)
            {
                Alert("Assessment deleted successfully.", AlertType.success);
            }
            else
            {
                Alert("Assessment could not be deleted.", AlertType.warning);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

SustiVest.Web/Controllers/DepositRequestController.cs
using Microsoft.AspNetCore.Mvc;
using SustiVest.Data.Entities;
using SustiVest.Data.Services;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SustiVest.Web.Controllers
{
    [Authorize(Roles = "admin, analyst, investor")]
    public class DepositRequestController : BaseController
    {
        private readonly IDepositRequestService _svc;

        public DepositRequestController(IDepositRequestService svc)
        {
            _svc = svc;
        }

        // GET /depositrequest
        [Authorize(Roles = "admin, analyst, investor")]
        [HttpGet]
        public IActionResult Details(int depositRequestNo)
        {
            var deposit = _svc.GetDepositRequest(depositRequestNo);
            if (deposit == null)
            {
                Alert("Deposit Request Not Found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            return View(deposit);
        }

        [Authorize(Roles = "admin, analyst, investor")]
        [HttpGet]
        public IActionResult Create(int offerId, string crNo)
        {
            var deposit = new DepositRequest
            {
                OfferId = offerId,
                CRNo = crNo,
                InvestorId = int.Parse(User.FindFirst(ClaimTypes.Sid).Value)
            };
            return View(deposit);
        }
      
        [Authorize(Roles = "admin, analyst, investor")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create([Bind("OfferId, Amount, InvestorId, CRNo, Status")] DepositRequest d)
        {
            if (ModelState.IsValid)
            {
                var deposit = _svc.Create(d);

                if (deposit == null)
                {
                    Alert("Encountered issue creating the deposit request", AlertType.warning);
                    return RedirectToAction(nameof(Index));
                }

                Alert("Deposit requested successfully ", AlertType.success);
                return RedirectToAction(nameof(Details), new { depositRequestNo = deposit.DepositRequestNo });
            }

            return View(d);
        }

            [Authorize(Roles = "admin, analyst")]
            [HttpGet]
            public IActionResult Edit(int depositRequestNo)
            {
                var deposit = _svc.GetDepositRequest(depositRequestNo);
                Console.WriteLine($"get deposit status: {deposit.Status}");
                if (deposit == null)
                {
                    Alert("Deposit Request Not Found", AlertType.warning);
                    return RedirectToAction(nameof(Index));
                }
                return View("Edit", deposit);
            }

            [Authorize(Roles = "admin, analyst")]
            [ValidateAntiForgeryToken]
            [HttpPost]
            public IActionResult Edit (DepositRequest d)
            
            {
                if (ModelState.IsValid)
                {
                    var updatedDeposit = _svc.Update(d);

                    if (updatedDeposit == null)
                    {
                        Alert("Encountered issue updating the deposit request", AlertType.warning);
                        return RedirectToAction(nameof(Index));
                    }
                    
                    Console.WriteLine($"Cont deposit status: {updatedDeposit.Status}");

                    Alert("Deposit request updated successfully ", AlertType.success);
                    return RedirectToAction(nameof(Details), new { depositRequestNo = updatedDeposit.DepositRequestNo });
                }

                return View(d);
            }

            [Authorize(Roles = "admin, analyst")]
            [HttpGet]
            public IActionResult Delete(int depositRequestNo)
            {
                var deposit = _svc.GetDepositRequest(depositRequestNo);
                if (deposit == null)
                {
                    Alert("Deposit Request Not Found", AlertType.warning);
                    return RedirectToAction(nameof(Index));
                }
                return View(deposit);
            }

            [Authorize(Roles = "admin, analyst")]
            [ValidateAntiForgeryToken]
            [HttpPost]
            public IActionResult DeleteConfirm(int depositRequestNo)
            {
                var deleted = _svc.DeleteDeposit(depositRequestNo);
                if (deleted)
                {
                    Alert("Deposit request deleted successfully.", AlertType.success);
                }
                else
                {
                    Alert("Deposit request could not  be deleted", AlertType.warning);
                }

                // redirect to the index view
                return RedirectToAction(nameof(Index));
            }

        [Authorize(Roles = "admin, analyst")]
        [HttpGet]
        public IActionResult Approve(int depositRequestNo)
        {
            var deposit = _svc.GetDepositRequest(depositRequestNo);
            if (deposit == null)
            {
                Alert("Deposit Request Not Found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return View(deposit);
        }

        [Authorize(Roles = "admin, analyst")]
        [HttpPost]
        public IActionResult Approve(DepositRequest d)
        {
            var depositRequest= _svc.GetDepositRequest(d.DepositRequestNo);
            
   
            if (ModelState.IsValid)
            {
                var depositApproved = _svc.ApproveDeposit(depositRequest);
                
                if (depositApproved == null)
                {
                    Alert("Encountered issue approving the deposit request", AlertType.warning);
                    return RedirectToAction(nameof(Index));
                }
                               
                Alert("Deposit request approved", AlertType.success);
                return RedirectToAction(nameof(Details), new { depositRequestNo = d.DepositRequestNo });
            }

            return View(d);
        }
        [Authorize(Roles = "admin, analyst")]
        public IActionResult Index(int page = 1, int size = 20, string orderBy = "DepositRequestNo", string direction = "asc")
        {
            var deposits = _svc.GetDeposits(page, size, orderBy, direction);
            return View(deposits);
        }

    }
}

SustiVest.Web/Views/Shared/Components/SortOrder/SortOrderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SustiVest.Web.Views.Shared.Components;

[ViewComponent]
public class SortOrderViewComponent : ViewComponent
{

    public IViewComponentResult Invoke(string field="Id", string orderby="Id", string direction = "asc")
    {      
        return View("Default", new SortOrderProps(field.ToLower(), orderby.ToLower(), direction.ToLower()) );
    }
}

public record SortOrderProps(string Field ="Id", string OrderBy="Id", string Direction="asc");

SustiVest.Web/Views/Offer/Create.cshtml
@model Offer

<div class="card rounded shadow p-4">
    <h3>Create Offer</h3>
    <form asp-action="Create">
       
        <div class="mt-3">
            <label asp-for="RequestNo" class="form-label">Request No</label>
            <input asp-for="RequestNo" class="form-control" />
            <span asp-validation-for="RequestNo" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="CRNo" class="form-label">CR No</label>
            <input asp-for="CRNo" class="form-control" />
            <span asp-validation-for="CRNo" class="text-danger"></span>
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="mt-3">
            <label asp-for="Amount" class="form-label">Amount</label>
            <input asp-for="Amount" class="form-control" />
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
             <div class="mt-3">
            <label asp-for="FundedAmount" class="form-label">Funded-To-Date</label>
            <input asp-for="FundedAmount" class="form-control" />
            <span asp-validation-for="FundedAmount" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Tenor" class="form-label">Tenor</label>
            <input asp-for="Tenor" class="form-control" />
            <span asp-validation-for="Tenor" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Payback" class="form-label">Payback</label>
            <input asp-for="Payback" class="form-control" />
            <span asp-validation-for="Payback" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Linens" class="form-label">Linens</label>
            <input asp-for="Linens" class="form-control" />
            <span asp-validation-for="Linens" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Undertakings" class="form-label">Undertakings</label>
            <input asp-for="Undertakings" class="form-control" />
            <span asp-validation-for="Undertakings" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Covenants" class="form-label">Covenants</label>
            <input asp-for="Covenants" class="form-control" />
            <span asp-validation-for="Covenants" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="ROR" class="form-label">ROR</label>
            <input asp-for="ROR" class="form-control" />
            <span asp-validation-for="ROR" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="FacilityType" class="form-label">Facility Type</label>
            <input asp-for="FacilityType" class="form-control" />
            <span asp-validation-for="FacilityType" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="UtilizationMechanism" class="form-label">Utilization Mechanism</label>
            <input asp-for="UtilizationMechanism" class="form-control" />
            <span asp-validation-for="UtilizationMechanism" class="text-danger"></span>
        </div>
        <div class="mt-3">
            <label asp-for="AnalystNo" class="form-label">Analyst No.</label>
            <input asp-for="AnalystNo" class="form-control" />
            <span asp-validation-for="AnalystNo" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="AssessmentNo" class="form-label">Assessment No.</label>
            <input asp-for="AssessmentNo" class="form-control" />
            <span asp-validation-for="AssessmentNo" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <button type="submit" name="submit" class="btn btn-primary" aria-label="Save">Save</button>
            <a class="btn btn-secondary" asp-action="Index" aria-label="Cancel">Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SustiVest.Web/Views/Offer/Details.cshtml
@model Offer

<partial name="_BreadCrumbs" model=@(new [] { ("/","Home"), ("/Offer","Offers"), ("",$"Offer {Model.RequestNo}-{Model.CRNo}") }) />

<div class="card rounded shadow p-4">
    <!-- Display offer details -->
    <div class="row">
        <!-- Details and Navigation -->
        <div class="col-8 d-flex flex-column justify-content-between">
            <!-- Offer details -->
            <div>
                <h2 class="mb-4 text-primary">Offer @Model.OfferId Details</h2>
                <dl class="row">
                    <dt class="col-4 pb-1">Request No.</dt>
                    <dd class="col-8 pb-1">@Model.RequestNo</dd>

                    <dt class="col-4 pb-1">CR No</dt>
                    <dd class="col-8 pb-1">@Model.CRNo</dd>
 
                    <dt class="col-4 pb-1">Amount</dt>
                    <dd class="col-8 pb-1">@Model.Amount</dd>

                    <dt class="col-4 pb-1">Funded-To-Date</dt>
                    <dd class="col-8 pb-1">@Model.FundedAmount</dd>

                    <dt class="col-4 pb-1">Still to Fund</dt>
                    <dd class="col-8 pb-1">@Model.RemainingToFund</dd>

                    <dt class="col-4 pb-1">Tenor</dt>
                    <dd class="col-8 pb-1">@Model.Tenor</dd>

                    <dt class="col-4 pb-1">Payback</dt>
                    <dd class="col-8 pb-1">@Model.Payback</dd>

                    <dt class="col-4 pb-1">Linens</dt>
                    <dd class="col-8 pb-1">@Model.Linens</dd>

                    <dt class="col-4 pb-1">Undertakings</dt>
                    <dd class="col-8 pb-1">@Model.Undertakings</dd>

                    <dt class="col-4 pb-1">Covenants</dt>
                    <dd class="col-8 pb-1">@Model.Covenants</dd>

                    <dt class="col-4 pb-1">ROR</dt>
                    <dd class="col-8 pb-1">@Model.ROR</dd>

                    <dt class="col-4 pb-1">Facility Type</dt>
                    <dd class="col-8 pb-1">@Model.FacilityType</dd>

                    <dt class="col-4 pb-1">Utilization Mechanism</dt>
                    <dd class="col-8 pb-1">@Model.UtilizationMechanism</dd>

                    <dt class="col-4 pb-1">Analyst No.</dt>
                    <dd class="col-8 pb-1">@Model.AnalystNo</dd>

                    <dt class="col-4 pb-1">Assessment</dt>
                    <dd class="col-8 pb-1"><a asp-controller="Assessments" asp-action="Details" asp-route-assessmentNo="@Model.AssessmentNo">View
                    Assessment</a></dd>
                    @{if (User.Identity.IsAuthenticated)
                    {
                        var userId= int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.Sid).Value);

                         if (userId == Model.Company.RepId  || User.IsInRole("admin") || User.IsInRole("analyst"))
                            {
                                <dt class="col-4 pb-1">Posted</dt>
                                @if (Model.Posted)
                                {
                                    <dd class="col-8 pb-1">Yes</dd>
                                }
                                else
                                {
                                    <dd class="col-8 pb-1">No</dd>
                                }
                    
                            }
                    }
                    }
                    
                </dl>
            </div>

            <!-- Navigation links -->
            <div>
                <a asp-action="Index" class="btn btn-sm btn-outline-primary" aria-label="offer list">
                    <i class="bi bi-list" title="offer list"></i>
                    <span class="ms-1 d-none d-md-inline">List</span>
                </a>

                <a asp-action="Edit" asp-route-offerId="@Model.OfferId"
                    class="btn btn-sm btn-outline-secondary" aria-label="edit offer">
                    <i class="bi bi-pen-fill" title="edit offer"></i>
                    <span class="ms-1 d-none d-md-inline">Edit</span>
                </a>
                <a asp-action="PostOffer" asp-route-offerId="@Model.OfferId"
                    class="btn btn-sm btn-outline-success" aria-label="post offer">
                    <i class="bi bi-confirm-fill" title="post offer"></i>
                    <span class="ms-1 d-none d-md-inline">Post</span>
                </a>

                <a asp-action="Delete" asp-route-offerId="@Model.OfferId">
                    <button type="button" class="btn btn-sm btn-outline-danger" aria-label="delete offer">
                        <i class="bi bi-trash-fill me-2" title="delete offer" aria-label="delete offer"></i>Delete
                    </button>
                </a>
                <a asp-controller="DepositRequest" asp-action="Create" asp-route-offerId="@Model.OfferId"
                asp-route-crNo="@Model.CRNo" class="btn btn-sm btn-outline-success" aria-label="create deposit">
                    <i class="bi bi-pen-fill" title="create deposit"></i>
                    <span class="ms-1 d-none d-md-inline">Fund</span>
                </a>
            </div>
        </div>
    </div>
</div>

SustiVest.Web/Views/Offer/Index.cshtml
@model Paged<Offer>

<partial name="_Breadcrumbs" model=@(new [] { ("/", "Home"), ("", "Offers") }) />

<div class="card border rounded shadow p-4">
    <!-- Title bar -->
    <div class="d-flex align-items-center justify-content-between">
        <h3>Offers</h3>
        <a class="btn btn-sm btn-primary" asp-action="Create" title="Create Offer" aria-label="Create Offer"
            style="background-color: #097969;">
            <i class="bi bi-plus text-white"></i> Create
        </a>

    </div>

    <!-- List of offers -->
    <table class="table table-hover mt-4">
        <thead>
            <tr>
                <th>
                    OfferId
                    <a asp-action="Index" asp-route-order="offerId" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="offerId" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                    CR No
                    <a asp-action="Index" asp-route-order="crNo" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="crNo" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                    Amount
                    <a asp-action="Index" asp-route-order="amount" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="amount" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                        Funded-To-Date 
                    <a asp-action="Index" asp-route-order="fundedAmount" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="fundedAmount" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                    Tenor
                    <a asp-action="Index" asp-route-order="tenor" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="tenor" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                    ROR
                    <a asp-action="Index" asp-route-order="ror" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="ror" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>
                    Facility Type
                    <a asp-action="Index" asp-route-order="facilityType" asp-route-direction=@Model.Direction
                        asp-route-page=@Model.CurrentPage asp-route-size=@Model.PageSize>
                        <vc:sort-order field="facilityType" orderby=@Model.OrderBy direction=@Model.Direction />
                    </a>
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var offer in Model.Data)
            {
                <tr>
                    <td>@offer.OfferId</td>
                    <td>@offer.CRNo</td>
                    <td>@offer.Amount</td>
                    <td>@offer.FundedAmount</td>
                    <td>@offer.Tenor</td>
                    <td>@offer.ROR</td>
                    <td>@offer.FacilityType</td>
                    <td>
                        <a asp-action="Details" asp-route-offerId="@offer.OfferId">
                            <i class="bi bi-display-fill me-2" title="View Offer" aria-label="View Offer"></i>
                        </a>
                        <a asp-action="Edit" asp-route-offerId="@offer.OfferId">
                            <i class="bi bi-pencil-fill me-2" title="Edit Offer" aria-label="Edit Offer"></i>
                        </a>
                        <a asp-action="Delete" asp-route-offerId="@offer.OfferId">
                            <i class="bi bi-trash-fill me-2" title="Delete Offer" aria-label="Delete Offer"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<style>
    .bi {
        color: #097969;
    }
</style>